import { COLORS } from "./colors";

export const styles = {
  root: {
    fontFamily: "'Georgia', serif",
    background: COLORS.bg,
    minHeight: "100vh",
    padding: "0 0 60px",
  },
  header: {
    background: `linear-gradient(160deg, #1b3a2d 0%, #2d6a4f 60%, #52b788 100%)`,
    color: "#fff",
    padding: "clamp(16px, 4vw, 36px) clamp(12px, 3vw, 24px) clamp(14px, 3vw, 28px)",
    textAlign: "center",
    position: "relative",
    overflow: "hidden",
  },
  headerLeaf: {
    position: "absolute",
    opacity: 0.07,
    fontSize: 220,
    top: -40,
    right: -20,
    pointerEvents: "none",
    lineHeight: 1,
  },
  badge: {
    display: "inline-block",
    background: "rgba(255,255,255,0.18)",
    border: "1px solid rgba(255,255,255,0.35)",
    borderRadius: 20,
    padding: "clamp(3px, 1vw, 4px) clamp(10px, 2vw, 16px)",
    fontSize: "clamp(10px, 2vw, 12px)",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    marginBottom: "clamp(8px, 2vw, 12px)",
  },
  title: {
    fontSize: "clamp(20px, 5.5vw, 32px)",
    fontWeight: "bold",
    margin: "0 0 clamp(4px, 1vw, 6px)",
    letterSpacing: "-0.5px",
  },
  subtitle: {
    fontSize: "clamp(12px, 3vw, 15px)",
    opacity: 0.85,
    maxWidth: 520,
    margin: "0 auto clamp(12px, 2vw, 16px)",
    lineHeight: 1.6,
  },
  missionBox: {
    background: "rgba(255,255,255,0.13)",
    border: "1px solid rgba(255,255,255,0.25)",
    borderRadius: 12,
    maxWidth: 600,
    margin: "0 auto",
    padding: "clamp(12px, 3vw, 14px) clamp(12px, 3.5vw, 20px)",
    fontSize: "clamp(12px, 2.8vw, 13.5px)",
    lineHeight: 1.7,
    textAlign: "left",
  },
  main: {
    maxWidth: 760,
    margin: "0 auto",
    padding: "0 clamp(8px, 2.5vw, 16px)",
  },
  progressSection: {
    margin: "clamp(16px, 3vw, 24px) 0 clamp(8px, 2vw, 8px)",
    background: COLORS.card,
    borderRadius: 14,
    border: `1px solid ${COLORS.border}`,
    padding: "clamp(12px, 2.5vw, 18px) clamp(12px, 3.5vw, 22px)",
  },
  progressLabel: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "clamp(8px, 2vw, 10px)",
    flexWrap: "wrap",
    gap: "clamp(8px, 2vw, 12px)",
  },
  progressBarBg: {
    background: COLORS.greenPale,
    borderRadius: 8,
    height: "clamp(10px, 2.5vw, 14px)",
    overflow: "hidden",
    minHeight: 10,
  },
  progressBarFill: (pct) => ({
    background: `linear-gradient(90deg, ${COLORS.green} 0%, ${COLORS.greenLight} 100%)`,
    height: "100%",
    width: `${pct}%`,
    borderRadius: 8,
    transition: "width 0.5s ease",
  }),
  legend: {
    display: "flex",
    gap: "clamp(12px, 3vw, 20px)",
    justifyContent: "flex-end",
    margin: "clamp(8px, 2vw, 10px) 0 clamp(12px, 2vw, 16px)",
    fontSize: "clamp(12px, 2.5vw, 13px)",
    color: COLORS.muted,
    flexWrap: "wrap",
  },
  legendDot: (color) => ({
    width: 14,
    height: 14,
    borderRadius: 4,
    background: color,
    border: `1px solid ${COLORS.border}`,
    display: "inline-block",
    verticalAlign: "middle",
    marginRight: 5,
  }),
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(10, 1fr)",
    gap: 6,
    margin: "0 0 28px",
  },
  numBtn: (sold, hover) => ({
    aspectRatio: "1",
    borderRadius: 6,
    border: sold ? `1.5px solid #c97a7a` : `1.5px solid ${COLORS.greenLight}`,
    background: sold ? COLORS.sold : hover ? COLORS.freeHover : COLORS.free,
    color: sold ? COLORS.soldText : hover ? "#ffffff" : COLORS.green,
    fontFamily: "'Georgia', serif",
    fontSize: "clamp(9px, 2vw, 13px)",
    fontWeight: sold ? "bold" : "normal",
    opacity: sold ? 0.7 : 1,
    cursor: sold ? "default" : "pointer",
    transition: "all 0.15s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    boxShadow: sold ? "none" : "0 1px 3px rgba(0,0,0,0.06)",
    padding: 0,
    minWidth: 0,
    minHeight: "clamp(28px, 7vw, 48px)",
  }),
  drawSection: {
    background: COLORS.amberPale,
    border: `2px solid ${COLORS.amberLight}`,
    borderRadius: 16,
    padding: "clamp(20px, 4vw, 28px) clamp(16px, 3vw, 24px)",
    textAlign: "center",
    margin: "0 0 clamp(16px, 3vw, 24px)",
  },
  drawBtn: {
    background: `linear-gradient(135deg, ${COLORS.amber} 0%, ${COLORS.amberLight} 100%)`,
    color: "#fff",
    border: "none",
    borderRadius: 12,
    padding: "clamp(10px, 2.5vw, 16px) clamp(18px, 5vw, 44px)",
    fontSize: "clamp(13px, 3.5vw, 18px)",
    fontFamily: "'Georgia', serif",
    fontWeight: "bold",
    cursor: "pointer",
    letterSpacing: "0.03em",
    boxShadow: "0 4px 16px rgba(181,96,10,0.3)",
    transition: "transform 0.1s",
    width: "100%",
    maxWidth: 320,
  },
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(27,58,45,0.55)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
    padding: "clamp(12px, 3vw, 20px)",
    overflowY: "auto",
  },
  modal: {
    background: COLORS.card,
    borderRadius: 18,
    padding: "clamp(18px, 4vw, 32px) clamp(14px, 4vw, 28px) clamp(18px, 3vw, 24px)",
    width: "100%",
    maxWidth: 380,
    boxShadow: "0 20px 60px rgba(27,58,45,0.25)",
    position: "relative",
    maxHeight: "90vh",
    overflowY: "auto",
  },
  modalTitle: {
    fontSize: "clamp(18px, 4vw, 22px)",
    color: COLORS.green,
    fontWeight: "bold",
    margin: "0 0 4px",
  },
  modalSub: {
    color: COLORS.muted,
    fontSize: "clamp(12px, 3vw, 14px)",
    margin: "0 0 clamp(16px, 3vw, 22px)",
  },
  label: {
    display: "block",
    fontSize: "clamp(11px, 2.5vw, 13px)",
    color: COLORS.muted,
    marginBottom: 4,
    fontFamily: "Arial, sans-serif",
  },
  input: {
    width: "100%",
    border: `1.5px solid ${COLORS.border}`,
    borderRadius: 8,
    padding: "clamp(8px, 2vw, 10px) clamp(10px, 2.5vw, 13px)",
    fontSize: "clamp(13px, 2.5vw, 15px)",
    marginBottom: "clamp(12px, 2.5vw, 16px)",
    outline: "none",
    fontFamily: "Arial, sans-serif",
    background: "#f7fdf9",
    boxSizing: "border-box",
    color: COLORS.text,
  },
  saveBtn: {
    width: "100%",
    background: COLORS.green,
    color: "#fff",
    border: "none",
    borderRadius: 10,
    padding: "clamp(10px, 2.5vw, 13px)",
    fontSize: "clamp(14px, 2.5vw, 16px)",
    fontFamily: "'Georgia', serif",
    fontWeight: "bold",
    cursor: "pointer",
    marginTop: 4,
  },
  cancelBtn: {
    width: "100%",
    background: "transparent",
    color: COLORS.muted,
    border: "none",
    fontSize: "clamp(12px, 2.5vw, 14px)",
    fontFamily: "Arial, sans-serif",
    cursor: "pointer",
    marginTop: "clamp(8px, 2vw, 10px)",
    padding: "6px",
  },
  infoCard: {
    background: COLORS.card,
    borderRadius: 14,
    border: `1px solid ${COLORS.border}`,
    padding: "clamp(12px, 3vw, 18px) clamp(12px, 3vw, 18px)",
    fontSize: "clamp(12px, 2.5vw, 13.5px)",
    color: COLORS.text,
    lineHeight: 1.6,
  },
  winnerModal: {
    background: COLORS.card,
    borderRadius: 20,
    padding: "clamp(20px, 5vw, 40px) clamp(14px, 4vw, 32px) clamp(18px, 4vw, 28px)",
    width: "100%",
    maxWidth: 400,
    textAlign: "center",
    boxShadow: "0 20px 60px rgba(27,58,45,0.3)",
    position: "relative",
    maxHeight: "90vh",
    overflowY: "auto",
  },
};
